version: 1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: UqWZWUV6GnaeDqFmDLkSDMGAZt8vMCnF6sgg1J3kRCrtV2XM37b6hr/SWRPeET39
before_build:
  - cmd: cd ./src
  - cmd: dotnet restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: NuGetPackage
deploy:
- provider: NuGet
  api_key:
    secure: xfvf8mYfM/WhwIgrec9Ls9XntziINAuvA16H5NQbUa4TkCCaa5iHV0r4vwE5W2QH
  on:
    branch: master
  artifact: NuGetPackage
test_script:
- ps: >-
    nuget install OpenCover -OutputDirectory packages
    dotnet tool install coveralls.net --tool-path tools
    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:xunit.console.clr4.exe "-targetargs:""tests\Bizy.OuinneBiseSharp.Tests\bin\Debug\netcoreapp2.0\Bizy.OuinneBiseSharp.Tests.dll"" /noshadow /appveyor" -filter:"+[OuinneBiseSharp*]*" -output:opencoverCoverage.xml
    $coveralls = ".\tools\csmacnz.coveralls.exe"
    "&" $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
