version: 1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - cmd: cd ./src
  - cmd: dotnet restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: xfvf8mYfM/WhwIgrec9Ls9XntziINAuvA16H5NQbUa4TkCCaa5iHV0r4vwE5W2QH
  on:
    branch: master
  artifact: /.*\.symbols\.nupkg/
